title <- "Music imagery test"

pages <- 
  withTags(
    list(new("one_btn_page",
             body = p("The Pitch Imagery Arrow Task has been designed to teach you to successfully imagine musical tones from a visual prompt.")),
         new("one_btn_page",
             body = p("Each trial starts with the word “Begin” on the screen, and you will hear an ascending major scale, which provides the key or context for that trial. You will then see a dot on the screen and hear a start note. Press 'Next' for an example of this.")),
         new("video_stimulus_NAFC",
             prompt = p("Here is an example context:"),
             source = "training/Scale_C_ton.mp4",
             type = "mp4",
             response_options = "Next",
             wait = TRUE),
         new("one_btn_page",
             body = p("A variable number of up and/or down arrows will then appear in a sequence, with a corresponding tone, that is stepping up or down the scale. Press 'Next' for an example of these arrows appearing after the ascending scale and start note.")),
         new("video_stimulus_NAFC",
             prompt = p("Here is an example of arrows appearing after the ascending scale and start note:"),
             source = "training/Example_Trial_sounded_arr.mp4",
             type = "mp4",
             response_options = "Next",
             wait = TRUE),
         new("one_btn_page",
             body = p("At some point in the trial, an arrow is shown with no tone heard. Your job is to imagine that exact missing tone. Initially there is one tone to be imagined per trial, but the number of tones to be imagined increases over the task, up to 5 tones. The word “hold” will appear with the last silent arrow of the sequence. Hold in your mind the sound of this last tone as you prepare to hear a test tone. Press 'Next' for an example of a single silent arrow added to our trial example.")),
         new("video_stimulus_NAFC",
             prompt = p("Here is an example:"),
             source = "training/Example_Trial_all_arr.mp4",
             type = "mp4",
             response_options = "Next",
             wait = TRUE),
         new("one_btn_page",
             body = p("To test the accuracy of your imagery, a test tone will be sounded and a white fixation cross will display. The tone will either match the note you are imagining, or will be incorrect. If the tone is correct press the left mouse button, if it is incorrect, press the right mouse button. Press 'Next' for the full example trial and try to respond correctly.")),
         new("video_stimulus_NAFC",
             prompt = p("Here is an example complete trial:"),
             source = "training/Example_Trial_complete.mp4",
             type = "mp4",
             response_options = "Next",
             wait = TRUE),
         new("one_btn_page",
             body = p("Most importantly, there is to be no cheating. This is a pitch imagery task, so no humming or moving is allowed to help you imagine. Your goal is to as vividly as possible, imagine these tones and keep the rest of your body still.")),
         new("one_btn_page",
             body = p("There are 3 practice trials in which you will receive feedback. You are free to attempt these as many times as you wish to familiarise yourself with the task. Once you are ready to start click <Start>. There are 30 trials to complete, starting with one imagined tone per trial and increasing gradually up to five imagined tones per trial. After completing the task, there are a few feedback questions to respond to.")),
         # new("repeatable_module", -- Store states inside the module object?
         #     repeat_prompt = p("Would you like to take the pratice questions again?"),
         #     module_content = list()
         #     )
         new("final_page",
             body = p("You completed the test! You may now close the browser window."))))
